version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      EMAIL_USE_SSL: 1
      EMAIL_USE_TLS: 1
      EMAIL_HOST: smtp.gmail.com
      EMAIL_HOST_USER: user_name
      EMAIL_HOST_PASSWORD: password
      EMAIL_PORT: 465
      DEFAULT_FROM_EMAIL: 587
      NEW_RELIC_CONFIG_FILE: /app/newrelic.ini
    command: newrelic-admin run-program python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
