version: "3.7"

x-app-config:
  &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key
  EMAIL_USE_SSL: 1
  EMAIL_USE_TLS: 1
  EMAIL_HOST: smtp.gmail.com
  EMAIL_HOST_USER: user_name
  EMAIL_HOST_PASSWORD: password
  EMAIL_PORT: 465
  DEFAULT_FROM_EMAIL: 587
  NEW_RELIC_CONFIG_FILE: /app/newrelic.ini
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  AWS_S3_REGION_NAME: ""
  REDIS_HOST: redis
  REDIS_PORT: 6379

x-db-config:
  &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword

services:
  api:
    build: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

volumes:
  sqlvolume:
